import { existsSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Plugin } from 'vite'

/**
 * Hand-rolled service worker generator.
 *
 * Why not vite-plugin-pwa? FORGED only needs two behaviours:
 *  1. precache the built app shell so the app opens with no network, and
 *  2. never serve a stale shell after a deploy.
 * ~60 lines of generated SW covers that with zero extra dependencies to audit,
 * which matters for an offline-first app that must keep working for years.
 *
 * All user data lives in IndexedDB, so the SW never needs to cache API calls.
 */
export function forgedServiceWorker(opts: { base: string }): Plugin {
  let outDir = 'dist'
  return {
    name: 'forged-service-worker',
    apply: 'build',
    configResolved(config) {
      outDir = config.build.outDir
    },
    writeBundle(_options, bundle) {
      const base = opts.base.endsWith('/') ? opts.base : `${opts.base}/`
      const assets = Object.keys(bundle)
        .filter((f) => !f.endsWith('.map'))
        .map((f) => base + f)
      const precache = Array.from(new Set([base, `${base}manifest.webmanifest`, ...assets]))
      // Icons live in public/ and never reach the rollup bundle. They are nice to
      // have offline but must not be able to fail the whole install, so they go
      // in a best-effort list rather than the required precache.
      const iconsDir = join(outDir, 'icons')
      const optional = existsSync(iconsDir)
        ? readdirSync(iconsDir).map((file) => `${base}icons/${file}`)
        : []
      // Cache name changes with content, so a deploy always invalidates the shell.
      const version = hash([...precache, ...optional].join('|'))
      writeFileSync(join(outDir, 'sw.js'), renderSw({ base, precache, optional, version }), 'utf8')
    },
  }
}

function hash(input: string): string {
  let h = 2166136261
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return (h >>> 0).toString(36)
}

function renderSw(o: {
  base: string
  precache: string[]
  optional: string[]
  version: string
}): string {
  return `// Generated by scripts/sw-plugin.ts — do not edit by hand.
const CACHE = 'forged-v${o.version}';
const PRECACHE = ${JSON.stringify(o.precache, null, 2)};
const OPTIONAL = ${JSON.stringify(o.optional, null, 2)};
const SHELL = '${o.base}index.html';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) =>
        cache
          .addAll(PRECACHE)
          .then(() => Promise.all(OPTIONAL.map((url) => cache.add(url).catch(() => undefined))))
      )
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: serve the cached shell first so the app opens instantly and
  // works with no network. Routing is hash-based, so one shell covers every route.
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match(SHELL).then((cached) => cached || fetch(req).catch(() => caches.match(SHELL)))
    );
    return;
  }

  // Static assets are content-hashed: cache-first, then fill the cache.
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res && res.status === 200 && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => cached);
    })
  );
});
`
}
